// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZpzYp9FfpYEvxhg0aAi16_mRw9dVLHhI',
    appId: '1:388249786676:web:5b76229a80b521cb836d61',
    messagingSenderId: '388249786676',
    projectId: 'test-89ac5',
    authDomain: 'test-89ac5.firebaseapp.com',
    storageBucket: 'test-89ac5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYokpGj34dDTyfdsJ3L28BlcjO4ZEuBU4',
    appId: '1:388249786676:android:c05b0eb4312ef576836d61',
    messagingSenderId: '388249786676',
    projectId: 'test-89ac5',
    storageBucket: 'test-89ac5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQyO3-Z7ot_SOIqNWBF4p1G1ZRIxQgj78',
    appId: '1:388249786676:ios:51d154bdda40491b836d61',
    messagingSenderId: '388249786676',
    projectId: 'test-89ac5',
    storageBucket: 'test-89ac5.firebasestorage.app',
    iosBundleId: 'com.example.untitled2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQyO3-Z7ot_SOIqNWBF4p1G1ZRIxQgj78',
    appId: '1:388249786676:ios:51d154bdda40491b836d61',
    messagingSenderId: '388249786676',
    projectId: 'test-89ac5',
    storageBucket: 'test-89ac5.firebasestorage.app',
    iosBundleId: 'com.example.untitled2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZpzYp9FfpYEvxhg0aAi16_mRw9dVLHhI',
    appId: '1:388249786676:web:f6f6ba1a37464d9f836d61',
    messagingSenderId: '388249786676',
    projectId: 'test-89ac5',
    authDomain: 'test-89ac5.firebaseapp.com',
    storageBucket: 'test-89ac5.firebasestorage.app',
  );
}
